"""
Production code for multi-pass blocking module for the AllianceChicago eMPI pipeline.
FINALIZED BLOCKING SCHEME (8 blocks):
    B1  — SSN Exact
    B3  — Double Metaphone (LastNM) + Full DOB
    B4  — LastNM Exact + BirthYear + FirstNM Prefix (3 chars)
    B5  — Phone Set Intersection (any phone match)
    B6  — Email Exact
    B7  — Double Metaphone (LastNM) + ZIP + BirthYear
    B8  — Soundex (FirstNM) + Soundex (LastNM) + BirthYear
    B9  — LastNM + FirstNM + SSN Last 4
 
NOTE — B2 REMOVED:
    B2 (LastNM Exact + Full DOB) was removed because it is mathematically
    subsumed by B3 (DM-LastNM + Full DOB). Double Metaphone groups exact
    name matches into the same phonetic code, so every pair B2 generates
    is also generated by B3. A3 Redundancy Analysis confirmed 0 unique
    pairs contributed by B2. Removal is an architectural consolidation,
    not a finding that exact name matching is unimportant.
 
PUBLIC API:
    build_blocking_index(df_clean)        -> BlockingIndex
    run_batch_blocking(df_clean)          -> pd.DataFrame
    run_inference_blocking(new_record,
                           blocking_index) -> pd.DataFrame
    compute_new_record_keys(new_record)   -> dict[str, object]
    hash_block_key(value)                 -> str
    get_blocking_stats(candidate_pairs)   -> dict
 
OUTPUT SCHEMA (candidate pairs DataFrame):
    PATID_A          str   — canonical first PATID (alphabetically lower)
    PATID_B          str   — canonical second PATID
    source_blocks    str   — pipe-delimited block IDs (e.g. "B3|B5|B8")
    n_blocks         int   — count of blocks that generated this pair
 
SPLINK COMPATIBILITY:
    The output DataFrame is directly compatible with splink's
    DedupingLinker when passed as pre-computed candidate pairs.
    Column names PATID_A / PATID_B match splink's unique_id_column_name
    convention with _l / _r suffixes handled internally by splink.
 
DEPENDENCIES:
    pip install jellyfish phonetics pandas pyarrow
 
HIPAA NOTE:
    This module never writes PHI to logs. All logging uses aggregate
    counts only. The source_blocks metadata enables full audit traceability
    without exposing field-level values.
"""

from __future__ import annotations

import ast
import hashlib
import logging
from dataclasses import dataclass, field
from datetime import datetime
from itertools import combinations
from pathlib import Path

import jellyfish
import pandas as pd
import numpy as np
import phonetics

from src.config import settings

logger = logging.getLogger(__name__)

# -----------Column Name Constraints-------------------
COL_PATID        = "PATID"
COL_LAST_NM      = "LastNM_clean"
COL_FIRST_NM     = "FirstNM_clean"
COL_BIRTH_DT     = "BirthDT_clean"
COL_SSN          = "SSN_clean"
COL_SSN_LAST4    = "last_4_SSN"          # pre-computed by cleaning pipeline
COL_ZIP          = "ZipCD_clean_base"
COL_EMAIL        = "Email_clean"
COL_PHONES       = "Phones_set"          # string-serialized set from pipeline
 
# Derived column names (computed internally)
_COL_DM_LN      = "_dm_LastNM"
_COL_SX_LN      = "_sx_LastNM"
_COL_SX_FN      = "_sx_FirstNM"
_COL_DOB_STR    = "_dob_str"
_COL_BIRTH_YEAR = "_birth_year"
_COL_FN_PRE3    = "_fn_prefix3"
_COL_PHONES_SET = "_phones_parsed"
 
# Governance threshold — blocks with more records than this are capped.
# Sourced from the central config (override via EMPI_GOVERNANCE_THRESHOLD).
GOVERNANCE_THRESHOLD = settings.governance_threshold

# Column produced by the cleaning pipeline marking record-level validity.
# Records with valid_record == False are excluded from blocking.
COL_VALID_RECORD = "valid_record"


def _filter_valid_records(df: pd.DataFrame) -> pd.DataFrame:
    """Drop rows flagged invalid by the cleaning pipeline.

    Records where `valid_record` is False (or its string equivalents from a
    `dtype=str` CSV read) are excluded. Rows with missing/NaN values are
    kept — only an explicit False drops the record. If the column is absent,
    the input is returned unchanged with a warning.
    """
    if COL_VALID_RECORD not in df.columns:
        logger.warning(
            "No '%s' column found — proceeding without validity filter. "
            "All %d records will be blocked.",
            COL_VALID_RECORD, len(df),
        )
        return df

    col = df[COL_VALID_RECORD]
    falsy = {False, "False", "false", "FALSE", "0", 0}
    mask = ~col.isin(falsy)

    n_before = len(df)
    df_filtered = df[mask].copy()
    n_dropped = n_before - len(df_filtered)
    logger.info(
        "Validity filter: dropped %d invalid records (valid_record=False); "
        "%d records remain for blocking",
        n_dropped, len(df_filtered),
    )
    return df_filtered

#-------Phonetic Encoding Functions----------------

def _dm_primary(name: str) -> str | None:
    """Double Metaphone primary code. Returns None on invalid input."""
    if not isinstance(name, str) or name.strip() == "":
        return None
    try:
        result = phonetics.dmetaphone(name)
        return result[0] if result[0] else None
    except Exception:
        return None
 
 
def _soundex(name: str) -> str | None:
    """Soundex code. Returns None on invalid input."""
    if not isinstance(name, str) or name.strip() == "":
        return None
    try:
        return jellyfish.soundex(name)
    except Exception:
        return None
 
#------Phone set Parser----------------------
def _parse_phone_set(value) -> set:
    """
    Parse a string-serialized phone set back to a Python set of strings.
 
    The cleaning pipeline serializes Phones_set as a string representation
    of a Python set (e.g. "{'7735551234', '3125559876'}"). This function
    handles all observed serialization formats.
    """
    if isinstance(value, (set, frozenset, list, tuple, np.ndarray)):
        # Parquet round-trips the pipeline's Phones_set list as an np.ndarray.
        return set(str(p).strip() for p in value if str(p).strip())
    if pd.isna(value):
        return set()
    if not isinstance(value, str):
        return set()
 
    value = value.strip()
    if value in ("", "nan", "None", "set()", "{}", "[]"):
        return set()
 
    try:
        parsed = ast.literal_eval(value)
        if isinstance(parsed, (set, list, tuple)):
            return set(str(p).strip() for p in parsed if str(p).strip())
    except (ValueError, SyntaxError, TypeError):
        pass
 
    # Fallback: strip delimiters and split by comma
    try:
        cleaned = value.strip("{}[]").replace("'", "").replace('"', "")
        return {p.strip() for p in cleaned.split(",") if p.strip()}
    except Exception:
        return set()
 

#----Pre-computation-------------------------

def _compute_derived_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute all derived columns required by the 8 blocking schemes.
    Returns a copy of df with derived columns appended.
    Idempotent — safe to call multiple times.
    """
    out = df.copy()
 
    # DOB-derived
    dob_parsed = pd.to_datetime(out[COL_BIRTH_DT], errors="coerce")
    out[_COL_DOB_STR]    = dob_parsed.dt.strftime("%Y-%m-%d")
    out[_COL_BIRTH_YEAR] = dob_parsed.dt.year.astype("Int64")
 
    # Name-derived
    out[_COL_FN_PRE3] = out[COL_FIRST_NM].str[:3]
    out[_COL_DM_LN]   = out[COL_LAST_NM].apply(
        lambda x: _dm_primary(x) if pd.notna(x) else None
    )
    out[_COL_SX_LN]   = out[COL_LAST_NM].apply(
        lambda x: _soundex(x) if pd.notna(x) else None
    )
    out[_COL_SX_FN]   = out[COL_FIRST_NM].apply(
        lambda x: _soundex(x) if pd.notna(x) else None
    )
 
    # Phone set — parse string serialization
    out[_COL_PHONES_SET] = out[COL_PHONES].apply(_parse_phone_set)
 
    logger.info(
        "Derived columns computed: DM-LN=%d, SX-LN=%d, SX-FN=%d, "
        "phones_parsed=%d",
        out[_COL_DM_LN].notna().sum(),
        out[_COL_SX_LN].notna().sum(),
        out[_COL_SX_FN].notna().sum(),
        (out[_COL_PHONES_SET].apply(len) > 0).sum(),
    )
    return out
 

#---Blocking index Dataclass----------------
@dataclass
class BlockingIndex:
    """
    Pre-built lookup structures for all 8 blocking schemes.
    Built once via build_blocking_index() and reused for inference
    without rebuilding on every new record.
    """
    # Non-phone blocks: {blocking_key_value -> [PATID, ...]}
    b1_index: dict = field(default_factory=dict)
    b3_index: dict = field(default_factory=dict)
    b4_index: dict = field(default_factory=dict)
    b6_index: dict = field(default_factory=dict)
    b7_index: dict = field(default_factory=dict)
    b8_index: dict = field(default_factory=dict)
    b9_index: dict = field(default_factory=dict)
    # Phone block: {phone_number -> {PATID, ...}}
    b5_phone_index: dict = field(default_factory=dict)
    # PATID -> phones set (for inference lookup)
    patid_phones: dict = field(default_factory=dict)
    # Metadata
    built_at: str = ""
    n_records: int = 0
 
 
def _build_key_index(df: pd.DataFrame, key_col: str) -> dict:
    """Build {key_value -> [PATID, ...]} from a dataframe and key column."""
    index: dict = {}
    for patid, key_val in zip(df[COL_PATID], df[key_col]):
        if pd.isna(key_val) or key_val == "":
            continue
        if key_val not in index:
            index[key_val] = []
        index[key_val].append(patid)
    return index
 
 
def _build_phone_index(df: pd.DataFrame) -> tuple[dict, dict]:
    """
    Build phone lookup structures for B5.
    Returns:
        phone_index:  {phone_number -> {PATID, ...}}
        patid_phones: {PATID -> {phone_number, ...}}
    """
    phone_index: dict = {}
    patid_phones: dict = {}
 
    for patid, phones in zip(df[COL_PATID], df[_COL_PHONES_SET]):
        if not phones:
            continue
        patid_phones[patid] = phones
        for phone in phones:
            if phone not in phone_index:
                phone_index[phone] = set()
            phone_index[phone].add(patid)
 
    return phone_index, patid_phones
 
 
def build_blocking_index(df_clean: pd.DataFrame) -> BlockingIndex:
    """
    Pre-compute all blocking key lookups from the cleaned dataset.
 
    Call this once at pipeline startup. The returned BlockingIndex is
    passed to run_inference_blocking() for each new incoming record.
 
    Parameters
    ----------
    df_clean : pd.DataFrame
        Fully cleaned dataset from the production cleaning pipeline.
 
    Returns
    -------
    BlockingIndex
        Pre-built lookup structures for all 8 blocking schemes.
    """
    logger.info("Building blocking index from %d records...", len(df_clean))
    df_clean = _filter_valid_records(df_clean)
    df = _compute_derived_columns(df_clean)
 

    #-----Build key columns-----------------
 
    sep = "|"  # pipe separator prevents false key collisions
 
    df["_k_b1"] = df[COL_SSN]
 
    df["_k_b3"] = np.where(
        df[_COL_DM_LN].notna() & df[_COL_DOB_STR].notna(),
        df[_COL_DM_LN].astype(str) + sep + df[_COL_DOB_STR],
        None,
    )
 
    df["_k_b4"] = np.where(
        df[COL_LAST_NM].notna() & df[_COL_BIRTH_YEAR].notna() & df[_COL_FN_PRE3].notna(),
        df[COL_LAST_NM].astype(str) + sep +
        df[_COL_BIRTH_YEAR].astype(str) + sep +
        df[_COL_FN_PRE3].astype(str),
        None,
    )
 
    df["_k_b6"] = df[COL_EMAIL]
 
    df["_k_b7"] = np.where(
        df[_COL_DM_LN].notna() & df[COL_ZIP].notna() & df[_COL_BIRTH_YEAR].notna(),
        df[_COL_DM_LN].astype(str) + sep +
        df[COL_ZIP].astype(str) + sep +
        df[_COL_BIRTH_YEAR].astype(str),
        None,
    )
 
    df["_k_b8"] = np.where(
        df[_COL_SX_FN].notna() & df[_COL_SX_LN].notna() & df[_COL_BIRTH_YEAR].notna(),
        df[_COL_SX_FN].astype(str) + sep +
        df[_COL_SX_LN].astype(str) + sep +
        df[_COL_BIRTH_YEAR].astype(str),
        None,
    )
 
    df["_k_b9"] = np.where(
        df[COL_LAST_NM].notna() & df[COL_FIRST_NM].notna() & df[COL_SSN_LAST4].notna(),
        df[COL_LAST_NM].astype(str) + sep +
        df[COL_FIRST_NM].astype(str) + sep +
        df[COL_SSN_LAST4].astype(str),
        None,
    )
 
    # ── Build indexes ──────────────────────────────────────────────────────
    b5_phone_index, patid_phones = _build_phone_index(df)
 
    index = BlockingIndex(
        b1_index    = _build_key_index(df, "_k_b1"),
        b3_index    = _build_key_index(df, "_k_b3"),
        b4_index    = _build_key_index(df, "_k_b4"),
        b6_index    = _build_key_index(df, "_k_b6"),
        b7_index    = _build_key_index(df, "_k_b7"),
        b8_index    = _build_key_index(df, "_k_b8"),
        b9_index    = _build_key_index(df, "_k_b9"),
        b5_phone_index = b5_phone_index,
        patid_phones   = patid_phones,
        built_at    = datetime.utcnow().isoformat(),
        n_records   = len(df_clean),
    )
 
    logger.info(
        "BlockingIndex built at %s | B1=%d keys | B3=%d | B4=%d | "
        "B5=%d phones | B6=%d | B7=%d | B8=%d | B9=%d",
        index.built_at,
        len(index.b1_index), len(index.b3_index), len(index.b4_index),
        len(index.b5_phone_index), len(index.b6_index),
        len(index.b7_index), len(index.b8_index), len(index.b9_index),
    )
    return index


#----Pair generation helpers----------------
def _pairs_from_index(
    index: dict,
    block_id: str,
    pair_blocks: dict,
) -> None:
    """
    Generate all canonical pairs from a blocking key index.
    Updates pair_blocks in-place: {(PATID_A, PATID_B) -> [block_id, ...]}
    """
    for key_val, patid_list in index.items():
        if len(patid_list) < 2:
            continue
        if len(patid_list) > GOVERNANCE_THRESHOLD:
            logger.warning(
                "Block %s: key value has %d records (>%d threshold). "
                "Applying governance cap.",
                block_id, len(patid_list), GOVERNANCE_THRESHOLD,
            )
            # Governance action: cap the candidate list at the configured threshold.
            patid_list = patid_list[:GOVERNANCE_THRESHOLD]
 
        for a, b in combinations(sorted(patid_list), 2):
            pair = (a, b)
            if pair not in pair_blocks:
                pair_blocks[pair] = []
            if block_id not in pair_blocks[pair]:
                pair_blocks[pair].append(block_id)
 
 
def _pairs_from_phone_index(
    phone_index: dict,
    pair_blocks: dict,
) -> None:
    """
    Generate canonical pairs from the phone set index for B5.
    Updates pair_blocks in-place.
    """
    for phone, patid_set in phone_index.items():
        patid_list = sorted(patid_set)
        if len(patid_list) < 2:
            continue
        if len(patid_list) > GOVERNANCE_THRESHOLD:
            logger.warning(
                "B5: phone number shared by %d records (>%d threshold). "
                "Likely clinic default phone — flagging for cleaning review.",
                len(patid_list), GOVERNANCE_THRESHOLD,
            )
            patid_list = patid_list[:GOVERNANCE_THRESHOLD]
 
        for a, b in combinations(patid_list, 2):
            pair = (a, b)
            if pair not in pair_blocks:
                pair_blocks[pair] = []
            if "B5" not in pair_blocks[pair]:
                pair_blocks[pair].append("B5")
 
 
def _pair_blocks_to_dataframe(pair_blocks: dict) -> pd.DataFrame:
    """Convert pair_blocks dict to the output DataFrame schema."""
    if not pair_blocks:
        return pd.DataFrame(columns=["PATID_A", "PATID_B",
                                      "source_blocks", "n_blocks"])
    rows = []
    for (patid_a, patid_b), blocks in pair_blocks.items():
        rows.append({
            "PATID_A":       patid_a,
            "PATID_B":       patid_b,
            "source_blocks": "|".join(sorted(blocks)),
            "n_blocks":      len(blocks),
        })
    return pd.DataFrame(rows)
 

# ---Batch blocking----------------
def run_batch_blocking(df_clean: pd.DataFrame) -> pd.DataFrame:
    """
    Run all 8 blocking schemes on the full cleaned dataset and return
    the deduplicated union of candidate pairs.
 
    This is the primary entry point for the batch pipeline. For the
    163,364-record AllianceChicago dataset this produces approximately
    212,908 unique candidate pairs (verified May 2026).
 
    Parameters
    ----------
    df_clean : pd.DataFrame
        Fully cleaned dataset from the production cleaning pipeline.
 
    Returns
    -------
    pd.DataFrame
        Deduplicated candidate pairs with schema:
            PATID_A       (str)
            PATID_B       (str)
            source_blocks (str)  pipe-delimited block IDs
            n_blocks      (int)  count of blocks generating this pair
    """
    logger.info(
        "Starting batch blocking on %d records...", len(df_clean)
    )
    start = datetime.utcnow()

    # Validity filtering is applied inside build_blocking_index — invalid
    # records (valid_record=False) never reach the indexes.
    index = build_blocking_index(df_clean)
    pair_blocks: dict = {}
 
    # ── Run each block ─────────────────────────────────────────────────────
    logger.info("Running B1 (SSN Exact)...")
    _pairs_from_index(index.b1_index, "B1", pair_blocks)
 
    logger.info("Running B3 (DM-LastNM + Full DOB)...")
    _pairs_from_index(index.b3_index, "B3", pair_blocks)
 
    logger.info("Running B4 (LastNM + BirthYear + FN-Prefix3)...")
    _pairs_from_index(index.b4_index, "B4", pair_blocks)
 
    logger.info("Running B5 (Phone Set Intersection)...")
    _pairs_from_phone_index(index.b5_phone_index, pair_blocks)
 
    logger.info("Running B6 (Email Exact)...")
    _pairs_from_index(index.b6_index, "B6", pair_blocks)
 
    logger.info("Running B7 (DM-LastNM + ZIP + BirthYear)...")
    _pairs_from_index(index.b7_index, "B7", pair_blocks)
 
    logger.info("Running B8 (Soundex-FN + Soundex-LN + BirthYear)...")
    _pairs_from_index(index.b8_index, "B8", pair_blocks)
 
    logger.info("Running B9 (LastNM + FirstNM + SSN-Last4)...")
    _pairs_from_index(index.b9_index, "B9", pair_blocks)
 
    # ── Build output DataFrame ─────────────────────────────────────────────
    candidate_pairs = _pair_blocks_to_dataframe(pair_blocks)
 
    elapsed = (datetime.utcnow() - start).total_seconds()
    logger.info(
        "Batch blocking complete in %.1fs | %d unique candidate pairs "
        "from %d records | reduction ratio: %.4f%%",
        elapsed,
        len(candidate_pairs),
        len(df_clean),
        100 * (1 - len(candidate_pairs) / max(
            len(df_clean) * (len(df_clean) - 1) / 2, 1
        )),
    )
 
    return candidate_pairs

#---Inference blocking----------------

#: The 7 scalar-key blocks, in the order `compute_new_record_keys` computes
#: them — B5 (phone) is multi-valued and handled separately by both callers.
_SCALAR_BLOCK_IDS: tuple[str, ...] = ("B1", "B3", "B4", "B6", "B7", "B8", "B9")

#: Block ids whose key values are direct identifiers (full SSN, email) rather
#: than an already-lossy derived signal (phonetic code, zip, birth year, name
#: prefix) — see `hash_block_key`. Consumed by `src/api/store.py`'s and
#: `src/api/parquet_backend.py`'s persisted block-key indexes; pure data, not
#: tied to either storage backend.
HASHED_BLOCKS: frozenset[str] = frozenset({"B1", "B6"})


def hash_block_key(value: str) -> str:
    """SHA-256 hex digest for a direct-identifier block key (SSN, email).

    Equality is the only operation ever performed on a persisted block key
    value, so hashing the two identifier-valued blocks (B1/SSN, B6/email)
    costs nothing functionally while keeping the persisted index from
    doubling as a second plaintext copy of those fields.
    """
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def compute_new_record_keys(new_record: dict | pd.Series) -> dict[str, object]:
    """
    Compute the 7 scalar blocking keys (B1/B3/B4/B6/B7/B8/B9) plus the parsed
    phone set (B5) for a single new/incoming record.

    Single source of truth for "what is this record's key for block X",
    shared by `run_inference_blocking` (in-memory `BlockingIndex` lookup) and
    the SQL-backed incremental lookup (`src/api/store.lookup_block_candidates`,
    used by `src/api/incremental.py`) — so the two paths can never define a
    block's key differently.

    Parameters
    ----------
    new_record : dict or pd.Series
        A single cleaned record. Must contain the same fields as df_clean.

    Returns
    -------
    dict[str, object]
        `{"B1": ..., "B3": ..., "B4": ..., "B6": ..., "B7": ..., "B8": ...,
        "B9": ..., "phones": set[str]}`. A scalar key is `None` when the
        record's fields can't produce it (missing/null inputs); `"phones"` is
        always a (possibly empty) set.
    """
    if isinstance(new_record, dict):
        new_record = pd.Series(new_record)

    sep = "|"

    ssn = new_record.get(COL_SSN)
    k_b1 = ssn if pd.notna(ssn) and ssn else None

    dob = pd.to_datetime(new_record.get(COL_BIRTH_DT), errors="coerce")
    dob_str = dob.strftime("%Y-%m-%d") if not pd.isna(dob) else None
    dm_ln = _dm_primary(new_record.get(COL_LAST_NM, ""))
    k_b3 = dm_ln + sep + dob_str if dm_ln and dob_str else None

    birth_year = dob.year if not pd.isna(dob) else None
    last_nm = new_record.get(COL_LAST_NM)
    first_nm = new_record.get(COL_FIRST_NM)
    fn_pre3 = str(first_nm)[:3] if pd.notna(first_nm) else None
    k_b4 = (
        str(last_nm) + sep + str(birth_year) + sep + fn_pre3
        if pd.notna(last_nm) and birth_year and fn_pre3 else None
    )

    email = new_record.get(COL_EMAIL)
    k_b6 = email if pd.notna(email) and email else None

    zip_cd = new_record.get(COL_ZIP)
    k_b7 = (
        dm_ln + sep + str(zip_cd) + sep + str(birth_year)
        if dm_ln and pd.notna(zip_cd) and birth_year else None
    )

    sx_fn = _soundex(str(first_nm)) if pd.notna(first_nm) else None
    sx_ln = _soundex(str(last_nm)) if pd.notna(last_nm) else None
    k_b8 = (
        sx_fn + sep + sx_ln + sep + str(birth_year)
        if sx_fn and sx_ln and birth_year else None
    )

    ssn_last4 = new_record.get(COL_SSN_LAST4)
    k_b9 = (
        str(last_nm) + sep + str(first_nm) + sep + str(ssn_last4)
        if pd.notna(last_nm) and pd.notna(first_nm) and pd.notna(ssn_last4)
        else None
    )

    return {
        "B1": k_b1, "B3": k_b3, "B4": k_b4, "B6": k_b6,
        "B7": k_b7, "B8": k_b8, "B9": k_b9,
        "phones": _parse_phone_set(new_record.get(COL_PHONES, "")),
    }


def run_inference_blocking(
    new_record: dict | pd.Series,
    blocking_index: BlockingIndex,
) -> pd.DataFrame:
    """
    Find all candidate pairs involving a single new record against the
    pre-built blocking index of existing records.

    Use this at inference time when a new PATID arrives and needs to be
    matched against the existing 163k patient index. The BlockingIndex
    is built once via build_blocking_index() and reused for every new
    record without rebuilding.

    Parameters
    ----------
    new_record : dict or pd.Series
        A single cleaned record. Must contain the same fields as df_clean.
        PATID field must be present and unique.
    blocking_index : BlockingIndex
        Pre-built index from build_blocking_index().

    Returns
    -------
    pd.DataFrame
        Candidate pairs involving the new record with schema:
            PATID_A       (str) — always the new record's PATID
            PATID_B       (str) — existing record's PATID
            source_blocks (str)
            n_blocks      (int)
    """
    if isinstance(new_record, dict):
        new_record = pd.Series(new_record)

    new_patid = new_record.get(COL_PATID)
    if not new_patid:
        raise ValueError("new_record must contain a non-null PATID field.")

    pair_blocks: dict = {}

    def _add_pair(existing_patid: str, block_id: str) -> None:
        """Add (new_patid, existing_patid) pair to pair_blocks."""
        # Always canonical: new record as PATID_A
        pair = (new_patid, existing_patid)
        if pair not in pair_blocks:
            pair_blocks[pair] = []
        if block_id not in pair_blocks[pair]:
            pair_blocks[pair].append(block_id)

    keys = compute_new_record_keys(new_record)
    index_by_block = {
        "B1": blocking_index.b1_index, "B3": blocking_index.b3_index,
        "B4": blocking_index.b4_index, "B6": blocking_index.b6_index,
        "B7": blocking_index.b7_index, "B8": blocking_index.b8_index,
        "B9": blocking_index.b9_index,
    }
    for block_id in _SCALAR_BLOCK_IDS:
        key_value = keys[block_id]
        if not key_value:
            continue
        for existing_patid in index_by_block[block_id].get(key_value, []):
            _add_pair(existing_patid, block_id)

    for phone in keys["phones"]:
        for existing_patid in blocking_index.b5_phone_index.get(phone, set()):
            _add_pair(existing_patid, "B5")

    result = _pair_blocks_to_dataframe(pair_blocks)
    logger.info(
        "Inference blocking for PATID %s: %d candidate pairs found",
        new_patid, len(result),
    )
    return result
 

#----Statistics & Audit----------------
def get_blocking_stats(candidate_pairs: pd.DataFrame) -> dict:
    """
    Compute audit statistics for a candidate pairs DataFrame.
 
    Returns a dict containing per-block pair counts, overlap stats,
    and the reduction ratio from the naive all-pairs baseline.
    Designed to populate the research paper Results section Table.
 
    Parameters
    ----------
    candidate_pairs : pd.DataFrame
        Output from run_batch_blocking().
        Must contain a 'PATID_A' column so n_records can be inferred
        for the naive pairs calculation, or pass n_records explicitly.

 
    Returns
    -------
    dict with keys:
        total_unique_pairs    int   — deduplicated pair count
        total_with_overlap    int   — sum of per block pair counts
        naive_pairs           int   - N*(N-1)/2 - estimated from unique PATIDs across both PATID columns
        reduction_pct         float - 100 * (1-unique/naive)
        overlap_pct           float - redundancy across blocks
        per_block             dict  - block_id -> pair count
        n_blocks_distribution dict  - n_blocks value -> pair count
    """
    if candidate_pairs.empty:
        return {}
 
    # Per-block pair counts (a pair in B3|B5 counts for both B3 and B5)
    block_counts: dict = {}
    for _, row in candidate_pairs.iterrows():
        for blk in row["source_blocks"].split("|"):
            block_counts[blk] = block_counts.get(blk, 0) + 1
 
    total_unique = len(candidate_pairs)
    total_with_overlap = sum(block_counts.values())
 
    #Infer N from the union of all PATIDs referenced in the pair set
    #This is a lower-bound estimate - the true N is the full dataset size,
    #which may include records that appear in no candidate pair (singletons).

    all_patids = pd.concat([
        candidate_pairs["PATID_A"],
        candidate_pairs["PATID_B"],
    ]).nunique()
    naive_pairs = all_patids * (all_patids - 1) // 2
    reduction_pct = round(
        100 * (1 - total_unique / naive_pairs), 6
    ) if naive_pairs > 0 else 0.0

    n_blocks_dist = candidate_pairs["n_blocks"].value_counts().sort_index().to_dict()
 
    return {
        "total_unique_pairs":    total_unique,
        "total_with_overlap":    total_with_overlap,
        "reduction_pct":         reduction_pct,
        "naive_pairs":           naive_pairs,
        "overlap_pct":           round(
            100 * (1 - total_unique / max(total_with_overlap, 1)), 1
        ),
        "per_block":             dict(sorted(block_counts.items())),
        "n_blocks_distribution": n_blocks_dist,
    }
 

#---Save / Load Helpers-----------------
def save_candidate_pairs(
    candidate_pairs: pd.DataFrame,
    output_path: str | Path,
    version: str = "v1",
) -> Path:
    """
    Save the candidate pairs DataFrame as a versioned parquet file.
    Parquet is the recommended format for downstream splink compatibility.
 
    Parameters
    ----------
    candidate_pairs : pd.DataFrame
    output_path : str or Path — directory or full file path
    version : str — version tag appended to filename
 
    Returns
    -------
    Path to the saved file.
    """
    #Verify pyarrow is available before attempting to write
    #Paquet requires either pyarrow or fastparquet. We standardize on pyarrow for consistency.
    #Raise a clear actionable error rather than letting pandas surface a cryptic ImportError.
    try:
        import pyarrow #noqa: F401
    except ImportError:
        try:
            import fastparquet #noqa: F401
        except ImportError:
            raise ImportError(
                "No parquet engine found. Please install pyarrow or fastparquet to save candidate pairs in parquet format.\n"
                "Install pyarrow to enable parquet output:\n"
                "    pip install pyarrow\n\n"
                "Candidate pairs were not saved. The in-memory DataFrame is still valid."
            ) from None
    output_path = Path(output_path)
    if output_path.is_dir():
        ts = datetime.utcnow().strftime("%Y_%m_%d")
        fname = f"candidate_pairs_{version}_{ts}.parquet"
        output_path = output_path / fname
 
    candidate_pairs.to_parquet(output_path, index=False)
    logger.info("Candidate pairs saved to %s (%d pairs)", output_path,
                len(candidate_pairs))
    return output_path
 

